# This is a basic workflow to help you get started with Actions

name: Send the DCP Report Announcement via Email

# Controls when the workflow will run
on:
    workflow_dispatch: # manual trigger
    workflow_run:
      workflows: [Auto-generate the Club DCP Report]
      types:
        - completed
      branches:
        - main
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  EMAIL_ID: ${{ vars.EMAIL_ID }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  CLUB_NUMBER: ${{ vars.CLUB_NUMBER }}
  CLUB_NAME: ${{ vars.CLUB_NAME }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install tools
        run: make install-tools

      - name: Send the notification via Email
        run: make -e send-notification
